// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Movie struct {
	ID    string  `json:"id"`
	Title *string `json:"title,omitempty"`
	Year  *int    `json:"year,omitempty"`
}

func (Movie) IsEntity() {}

type Query struct {
}
