name: apollo-federation-sample

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    depends_on:
      reviews:
        condition: service_started
      movies:
        condition: service_started

  reviews:
    build:
      context: ./subgraph/reviews
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
    volumes:
      - ./subgraph/reviews/data:/root/reviews.db

  movies:
    build:
      context: ./subgraph/movies
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
    volumes:
      - ./subgraph/movies/movies.db:/root/movies.db

networks:
  default:
    name: federation-network

