package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"movies/graph/model"
	"movies/internal/repository"
)

// FindMovieByID is the resolver for the findMovieByID field.
func (r *entityResolver) FindMovieByID(ctx context.Context, id string) (*model.Movie, error) {
	movies, err := r.MovieRepo.GetMovies(ctx, repository.WithID(id))
	if err != nil {
		return nil, err
	}
	if len(movies) == 0 {
		return nil, nil
	}
	return movies[0], nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
