package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"movies/graph/model"
	"movies/internal/repository"
)

// Movies is the resolver for the movies field.
func (r *queryResolver) Movies(ctx context.Context) ([]*model.Movie, error) {
	return r.MovieRepo.GetMovies(ctx)
}

// Movie is the resolver for the movie field.
func (r *queryResolver) Movie(ctx context.Context, id string) (*model.Movie, error) {
	movies, err := r.MovieRepo.GetMovies(ctx, repository.WithID(id))
	if err != nil {
		return nil, err
	}
	if len(movies) == 0 {
		return nil, nil
	}
	return movies[0], nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
