// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Movie struct {
	ID              string    `json:"id"`
	OverallRating   *float64  `json:"overallRating,omitempty"`
	ReviewsForMovie []*Review `json:"reviewsForMovie"`
}

func (Movie) IsEntity() {}

type MovieReviewInput struct {
	MovieID string  `json:"movieId"`
	Comment *string `json:"comment,omitempty"`
	Rating  *int    `json:"rating,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type SubmitReviewResponse struct {
	Code        int     `json:"code"`
	Success     bool    `json:"success"`
	Message     string  `json:"message"`
	MovieReview *Review `json:"movieReview,omitempty"`
}
