package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"reviews/graph/model"
	"reviews/internal/repository"
)

// FindMovieByID is the resolver for the findMovieByID field.
func (r *entityResolver) FindMovieByID(ctx context.Context, id string) (*model.Movie, error) {
	movie := &model.Movie{
		ID: id,
	}

	overallRating, err := r.ReviewRepo.GetOverallRatingForMovie(ctx, id)
	if err != nil {
		return nil, err
	}
	movie.OverallRating = &overallRating

	reviews, err := r.ReviewRepo.GetReviews(ctx, repository.WithMovieID(id))
	if err != nil {
		return nil, err
	}
	movie.ReviewsForMovie = reviews

	return movie, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
